#define IDD_PHRP_SR_RADIO_DIALOG  7829

#define IDC_PHRP_SR_BACKGROUND TF_IDD_BACKGROUND
#define IDC_PHRP_SR_EDIT  SW_EDIT
#define IDC_PHRP_SR_ENTER  7830
#define IDC_PHRP_SR_CLEAR  7831
#define IDC_PHRP_SR_NEXT  7832
#define IDC_PHRP_SR_PREV  7833
#define IDC_PHRP_SR_CHANNEL_EDIT  SW_CHANNEL
#define IDC_PHRP_SR_INCREASE_VOLUME 7834
#define IDC_PHRP_SR_DECREASE_VOLUME 7835
#define IDC_PHRP_SR_STEREO    7836
#define IDC_PHRP_SR_RADIO_DIALOG_ADDITIONAL ID_ADDITIONAL
#define IDC_PHRP_SR_SPEAKERS ID_SPEAKERS